import '../models/listing_item.dart';

class ListingRepository {
  static List<ListingItem> getInitialListings() {
    return [
      const ListingItem(
        id: 'deal_01',
        title: '2016 Toyota Axio 1.5 Hybrid',
        price: 4800,
        category: 'Vehicles',
        location: 'Harare Central',
        distanceKm: 4.2,
        isVerified: true,
        isFeatured: false,
        isNegotiable: true,
        images: [
          'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80',
        ],
        specs: {
          'Condition': 'Foreign Used',
          'Fuel Type': 'Petrol/Hybrid',
          'Mileage': '74,200 km',
          'Transmission': 'Automatic CVT',
        },
        description: 'Mint condition Toyota Axio 1.5 Hybrid. Push start, reverse camera, clean fabric interior, non-smoker. Genuine mileage, service history available at Croco Motors. Direct import, Zimbabwe duty fully paid.',
        allowsBarter: true,
        tradeDetails: 'Open to swap with Toyota Passo / Vitz + Cash top up',
        sellerName: 'Tendai M.',
        sellerPhone: '+263771234567',
        sellerRating: 4.9,
        sellerReviewsCount: 84,
        sellerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
        timeListedAgo: '2h ago',
        meetupSpot: 'Meikles Hotel Area - Harare CBD (Safe public spot)',
        latitude: -17.8292,
        longitude: 31.0522,
        tags: ['Hybrid', 'Clean', 'Verified Seller', 'Duty Paid'],
      ),
      const ListingItem(
        id: 'deal_02',
        title: 'iPhone 13 · 128GB Midnight',
        price: 380,
        category: 'Phones',
        location: 'Avondale, Harare',
        distanceKm: 3.0,
        isVerified: true,
        isFeatured: true,
        isNegotiable: true,
        images: [
          'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=800&auto=format&fit=crop&q=80',
        ],
        specs: {
          'Condition': 'Like New (9/10)',
          'Battery Health': '89%',
          'Storage': '128GB',
          'Color': 'Midnight Black',
        },
        description: 'Factory unlocked iPhone 13 128GB. 89% Battery Health, never opened or repaired. Comes with original USB-C to Lightning cable and clear protective case. FaceID and True Tone 100% working.',
        allowsBarter: true,
        tradeDetails: 'Accepting trade-in for iPhone 11 Pro / S21 + Cash',
        sellerName: 'Kudakwashe Z.',
        sellerPhone: '+263719876543',
        sellerRating: 4.8,
        sellerReviewsCount: 42,
        sellerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
        timeListedAgo: '45m ago',
        meetupSpot: 'Avondale Shopping Centre - Outside Cafe Nush',
        latitude: -17.7915,
        longitude: 31.0345,
        tags: ['89% Battery', 'Unlocked', 'Original Screen'],
      ),
      const ListingItem(
        id: 'deal_03',
        title: '5kVA Must Hybrid Solar Inverter + Lithium Pack',
        price: 1650,
        category: 'Solar & Power',
        location: 'Eastlea, Harare',
        distanceKm: 5.8,
        isVerified: true,
        isFeatured: false,
        isNegotiable: false,
        images: [
          'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&auto=format&fit=crop&q=80',
        ],
        specs: {
          'Condition': 'Brand New (Sealed)',
          'Capacity': '5000 Watts',
          'Battery Type': 'Lithium LiFePO4',
          'Warranty': '3 Years',
        },
        description: 'Complete backup power solution for load shedding in Zimbabwe. 5kW Pure Sine Wave 48V Inverter paired with 5.12kWh Felicity Solar LiFePO4 battery pack. Wifi monitoring dongle included.',
        allowsBarter: false,
        sellerName: 'Ruvimbo Chitepo',
        sellerPhone: '+263735551212',
        sellerRating: 5.0,
        sellerReviewsCount: 19,
        sellerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
        timeListedAgo: '3h ago',
        meetupSpot: 'Samora Machel Ave & Glenara Ave intersection',
        latitude: -17.8220,
        longitude: 31.0910,
        tags: ['Loadshedding', 'Lithium', 'Warranty'],
      ),
      const ListingItem(
        id: 'deal_04',
        title: 'Samsung Galaxy S22 Ultra 256GB Phantom Black',
        price: 510,
        category: 'Phones',
        location: 'Borrowdale, Harare',
        distanceKm: 8.4,
        isVerified: true,
        isFeatured: false,
        isNegotiable: true,
        images: [
          'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&auto=format&fit=crop&q=80',
        ],
        specs: {
          'Condition': 'Pristine (9.5/10)',
          'Storage': '256GB / 12GB RAM',
          'Camera': '108MP 100x Zoom',
          'SIM': 'Dual SIM',
        },
        description: 'Super clean flagship with built-in S-Pen. 12GB RAM, 256GB storage, Snapdragon chip. Dual physical SIM. Zero scratches on screen.',
        allowsBarter: true,
        tradeDetails: 'Will consider iPhone 12 Pro Max + \$50',
        sellerName: 'Tendai M.',
        sellerPhone: '+263771234567',
        sellerRating: 4.9,
        sellerReviewsCount: 84,
        sellerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
        timeListedAgo: '5h ago',
        meetupSpot: 'Sam Levy Village - Food Court Entrance',
        latitude: -17.7533,
        longitude: 31.0850,
        tags: ['S-Pen', 'Dual SIM', 'Snapdragon'],
      ),
      const ListingItem(
        id: 'deal_05',
        title: '2014 Honda Fit GP5 Hybrid',
        price: 3600,
        category: 'Vehicles',
        location: 'Belvedere, Harare',
        distanceKm: 2.5,
        isVerified: true,
        isFeatured: false,
        isNegotiable: true,
        images: [
          'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=800&auto=format&fit=crop&q=80',
        ],
        specs: {
          'Condition': 'Registered Local',
          'Engine': '1.5L Earth Dreams',
          'Fuel': 'Hybrid Petrol',
          'Transmission': 'Automatic',
        },
        description: 'Fuel efficient everyday city runner. Keyless entry, push start, eco drive mode, tinted windows, brand new tyres. Mileage 89,000km.',
        allowsBarter: true,
        tradeDetails: 'Open to barter with solar setup + cash',
        sellerName: 'Kudakwashe Z.',
        sellerPhone: '+263719876543',
        sellerRating: 4.8,
        sellerReviewsCount: 42,
        sellerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
        timeListedAgo: '6h ago',
        meetupSpot: 'Kambuzuma / Belvedere Total Garage',
        latitude: -17.8340,
        longitude: 31.0180,
        tags: ['GP5', 'Fuel Saver', 'Hybrid'],
      ),
      const ListingItem(
        id: 'deal_06',
        title: 'MacBook Air M1 2020 8GB / 256GB Space Gray',
        price: 590,
        category: 'Electronics',
        location: 'Mount Pleasant, Harare',
        distanceKm: 6.1,
        isVerified: true,
        isFeatured: false,
        isNegotiable: true,
        images: [
          'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&auto=format&fit=crop&q=80',
        ],
        specs: {
          'Condition': 'Like New',
          'Battery Health': '94%',
          'Processor': 'Apple M1 8-Core',
          'RAM': '8GB Unified',
        },
        description: 'Battery health 94%, cycle count 112. Immaculate condition with box and 30W adapter. Ideal for software devs, students, and remote work.',
        allowsBarter: true,
        tradeDetails: 'Trade: M1 MacBook Air for iPad Pro + Cash',
        sellerName: 'Ruvimbo Chitepo',
        sellerPhone: '+263735551212',
        sellerRating: 5.0,
        sellerReviewsCount: 19,
        sellerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
        timeListedAgo: '7h ago',
        meetupSpot: 'Arundel Village Shopping Centre',
        latitude: -17.7710,
        longitude: 31.0420,
        tags: ['Apple M1', '94% Battery', 'Box Included'],
      ),
    ];
  }
}
